name: iacg
description: "iACG Cosplay Platform"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_staggered_grid_view: ^0.7.0

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.1.0
  flutter_hooks: ^0.20.0
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  intl: ^0.19.0                 # 时间格式化等
  image_picker: ^1.1.0          # 选择图片 
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # 添加插件

# 应用图标
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon/IACG.jpg"  # 图标路径
  adaptive_icon_background: "#FFFFFF"  # Android 适应性图标背景色

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
